# Generated by Django 3.1.5 on 2021-01-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_link', models.URLField()),
                ('new_link', models.CharField(max_length=10)),
            ],
        ),
    ]
